// <auto-generated />
using System;
using FastWorkshopsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastWorkshopsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FastWorkshopsApi.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Colaboradores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ana Beatriz Costa"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Bruno Fernandes Lima"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Carla Menezes"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Diego Alves Souza"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Fernanda Ribeiro"
                        });
                });

            modelBuilder.Entity("FastWorkshopsApi.Models.Presenca", b =>
                {
                    b.Property<int>("WorkshopId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkshopId", "ColaboradorId");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("Presencas");

                    b.HasData(
                        new
                        {
                            WorkshopId = 1,
                            ColaboradorId = 1,
                            RegistradoEm = new DateTime(2026, 8, 13, 10, 55, 23, 818, DateTimeKind.Utc).AddTicks(9462)
                        },
                        new
                        {
                            WorkshopId = 1,
                            ColaboradorId = 2,
                            RegistradoEm = new DateTime(2026, 8, 13, 10, 55, 23, 818, DateTimeKind.Utc).AddTicks(9470)
                        },
                        new
                        {
                            WorkshopId = 1,
                            ColaboradorId = 3,
                            RegistradoEm = new DateTime(2026, 8, 13, 10, 55, 23, 818, DateTimeKind.Utc).AddTicks(9470)
                        },
                        new
                        {
                            WorkshopId = 2,
                            ColaboradorId = 1,
                            RegistradoEm = new DateTime(2026, 8, 13, 10, 55, 23, 818, DateTimeKind.Utc).AddTicks(9471)
                        },
                        new
                        {
                            WorkshopId = 2,
                            ColaboradorId = 4,
                            RegistradoEm = new DateTime(2026, 8, 13, 10, 55, 23, 818, DateTimeKind.Utc).AddTicks(9472)
                        },
                        new
                        {
                            WorkshopId = 2,
                            ColaboradorId = 5,
                            RegistradoEm = new DateTime(2026, 8, 13, 10, 55, 23, 818, DateTimeKind.Utc).AddTicks(9472)
                        });
                });

            modelBuilder.Entity("FastWorkshopsApi.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Workshops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataRealizacao = new DateTime(2025, 3, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Panorama prático sobre decomposição de sistemas monolíticos e comunicação entre serviços.",
                            Nome = "Introdução a Microsserviços"
                        },
                        new
                        {
                            Id = 2,
                            DataRealizacao = new DateTime(2025, 6, 19, 16, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Como organizar camadas e reduzir acoplamento em projetos reais da FAST.",
                            Nome = "Clean Architecture na Prática"
                        });
                });

            modelBuilder.Entity("FastWorkshopsApi.Models.Presenca", b =>
                {
                    b.HasOne("FastWorkshopsApi.Models.Colaborador", "Colaborador")
                        .WithMany("Presencas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastWorkshopsApi.Models.Workshop", "Workshop")
                        .WithMany("Presencas")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("FastWorkshopsApi.Models.Colaborador", b =>
                {
                    b.Navigation("Presencas");
                });

            modelBuilder.Entity("FastWorkshopsApi.Models.Workshop", b =>
                {
                    b.Navigation("Presencas");
                });
#pragma warning restore 612, 618
        }
    }
}
